<?php
$iType = array(
    1 => 'Resident Alcohol or Illicit Substance Abuse',
    2 => 'Observations of Resident Expressing Suicidality or Homicidally',
    3 => 'Resident Elopement',
    4 => 'Unauthorized Wing Visits',
    5 => 'Room Cleanliness Issues',
    6 => 'Smoking in Rooms',
    7 => 'Begging',
    8 => 'Excessive Request to Use Office Phone',
    9 => 'Disruptive Behavior in the Facility',
    10 => 'Disruptive Behavior in the Community',
    11 => 'Physical Aggression Toward Peer',
    12 => 'Physical Aggression Toward Staff',
    13 => 'Verbal Aggression Toward Peer: Posturing',
    14 => 'Verbal Aggression Toward Staff: Posturing',
    15 => 'Theft Events',
    16 => 'Loss of Belonging Events',
    17 => 'Medication Refusal',
    18 => 'Physical Health Concern',
    19 => 'Behavior (Rule Compliance)',
    20 => 'Behavior (Other)',
    21 => 'Disruptive Behavior on the Patio',
    22 => '911 - Psych',
    23 => '911 - Medical',
    24 => 'Hospital - Psych',
    25 => 'Hospital - Medical',
    26 => 'Disruptive Behavior in the Courtyard',
    27 => 'Return from Hospital',
    28 => 'Admission',
    29 => 'Risk Mitigation',
    30 => 'Medical Issue/Concern',
    31 => 'Appointment',
    32 => 'Death/Family Illness',
    33 => 'Resident Reported Success',
    34 => 'Citizenship Award',
    35 => 'Resident Restriction',
    36 => 'Discharged from Facility',
    37 => 'Communication with Discharged Resident',
    38 => 'Resident Vacation',
    39 => 'Bookkeeping',
    40 => 'Required Forms',
    41 => 'Community Outreach',
	42 => 'Out on Pass',
	43 => 'Return from Pass',

    90 => 'QAPI Suggestion',
    991 => 'Memo',
    992 => 'Dietary',
    993 => 'Maintenance',
    999 => 'Other',
);

asort($iType);
